#!/bin/bash

NUM_ACTOR_WORKER=5
NUM_CRITIC_WORKER=1
myip_command="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
myip=$(eval "$myip_command")

python train.py --config config/halfcheetah-v2/td3.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/acemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/opo.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/cemrl.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --parallel_critic --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update adaptive --aesrl_mean_update_param 2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update adaptive --aesrl_mean_update_param -2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update adaptive --aesrl_mean_update_param 2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update adaptive --aesrl_mean_update_param 2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update fixed --aesrl_mean_update_param 2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update fixed --aesrl_mean_update_param -2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update fixed --aesrl_mean_update_param 2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/halfcheetah-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update fixed --aesrl_mean_update_param 2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345

python train.py --config config/ant-v2/td3.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/acemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/opo.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/cemrl.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --parallel_critic --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update adaptive --aesrl_mean_update_param -960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update fixed --aesrl_mean_update_param -960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/ant-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345

python train.py --config config/hopper-v2/td3.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/acemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/opo.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/cemrl.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --parallel_critic --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update adaptive --aesrl_mean_update_param 2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update adaptive --aesrl_mean_update_param -2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update adaptive --aesrl_mean_update_param 2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update adaptive --aesrl_mean_update_param 2000 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update fixed --aesrl_mean_update_param 2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update fixed --aesrl_mean_update_param -2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update fixed --aesrl_mean_update_param 2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/hopper-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update fixed --aesrl_mean_update_param 2000 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345

python train.py --config config/humanoid-v2/td3.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/acemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/opo.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/cemrl.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --parallel_critic --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update adaptive --aesrl_mean_update_param -960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update fixed --aesrl_mean_update_param -960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/humanoid-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345

python train.py --config config/swimmer-v2/td3.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/acemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/opo.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/cemrl.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --parallel_critic --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update adaptive --aesrl_mean_update_param -960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update fixed --aesrl_mean_update_param -960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/swimmer-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345

python train.py --config config/walker2d-v2/td3.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/acemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/opo.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/cemrl.json --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/pcemrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --parallel_critic --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update adaptive --aesrl_mean_update_param -960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update adaptive --aesrl_mean_update_param 960 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-relative --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update baseline-absolute --aesrl_var_update fixed --aesrl_mean_update_param -960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-linear --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345
python train.py --config config/walker2d-v2/aesrl.json --num_actor_worker $NUM_ACTOR_WORKER --num_critic_worker $NUM_CRITIC_WORKER --aesrl_mean_update fixed-sigmoid --aesrl_var_update fixed --aesrl_mean_update_param 960 --aesrl_fixed_var_n 10 --ray_address $myip --ray_port 12345 --redis_password 12345

